[package]
name = "fuzz-targets-libfuzzer"
version = "0.0.0"
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
fuzz-targets-common = {path = "../targets"}

# Prevent this from interfering with workspaces
[workspace]
members = ["."]
